### ISSUE TITLE
ulice są niedostosowane do form OSM

### ISSUE THREAD

**Issue by ttomasz** [openstreetmap-polska/dane-rspo#1]
Może to mapowanie się przyda https://github.com/openstreetmap-polska/gugik2osm/blob/main/processing/sql/data/street_names_mappings.csv

**Comment by Pooh01pl** [comment]
Co robić z cechą (ul. / al. / pl. / os.)? We Wrocławiu ul. Piłsudskiego jest gdzie indziej niż pl. Piłsudskiego. 
Cechę doklejać zawsze czy tylko w przypadku cechy innej niż "ul"?

Sporo ulic w załączonym spisie nie istnieje, zastanawiam się czy mogę przez analogię skopiować nazwy OSMowe z innych miejscowości, bo jednak w OSM dokładane są często domyślne imiona do znanych nazwisk, a w jakimś konkretnym przypadku może to nie być prawdą.

Dla ulic, gdzie nie mamy nazwy w standardzie OSM, podstawiałbym to co jest wpisane w RSPO, bo w SIMC_ULIC też jest bałagan, niektóre nazwy z cechą inną niż "ul" zawierają cechę również w nazwie, a niektóre nie.

**Comment by ttomasz** [comment]
"ul." jest taką domyślną cechą i się go nie dodaje, reszta jest rozwijana (z wyjątkiem przypadków gdzie to duplikowało by się z nazwą np "Rynek Rynek" wtedy też jest ignorowane). Tę listę przygotowuje @mskakuj , zdziwiło by mnie gdyby czegoś brakowało, ale jak masz konkretne przykłady to pewnie można by uzupełnić.

**Comment by Pooh01pl** [comment]
Poprawione. Nazwy ulic dostosowano do standardów OSM.
Wspomniane przeze mnie wcześniej braki dotyczyły ulic, które mają poprawne nazwy same z siebie. Przy okazji okazało się, że w RSPO były błędy typu: "aleja Aleja kasztanowa".
